<<<<<<< HEAD
# Generated by Django 2.0.4 on 2018-05-18 03:04
=======
# Generated by Django 2.0.5 on 2018-05-18 03:23


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
