# Generated by Django 2.0.5 on 2018-05-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0002_team_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
