# Generated by Django 2.0.5 on 2018-06-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0006_auto_20180521_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='score',
        ),
    ]
