# Generated by Django 2.0.6 on 2018-06-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0008_auto_20180605_0145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together=set(),
        ),
    ]
