# Generated by Django 2.0.6 on 2018-06-06 16:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prode', '0009_auto_20180606_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together={('user', 'match')},
        ),
    ]
