# Generated by Django 2.0.5 on 2018-06-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0012_remove_match_end_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.ImageField(upload_to='prode/images/'),
        ),
    ]
