# Generated by Django 2.0.5 on 2018-06-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0013_auto_20180610_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.ImageField(upload_to='prode/images/flags/'),
        ),
    ]
