# Generated by Django 2.0.4 on 2018-06-19 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0015_auto_20180619_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='matches',
            new_name='match',
        ),
    ]
