# Generated by Django 2.0.4 on 2018-06-20 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prode', '0017_auto_20180619_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('ranking', models.PositiveIntegerField()),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prode.Bet')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prode.Competition')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
