# Generated by Django 2.0.4 on 2018-06-20 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0018_competitionstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionstats',
            name='bet',
        ),
        migrations.RemoveField(
            model_name='competitionstats',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='competitionstats',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompetitionStats',
        ),
    ]
