# Generated by Django 2.0.5 on 2018-06-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0019_auto_20180620_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
