# Generated by Django 2.0.4 on 2018-06-20 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0020_auto_20180620_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='user',
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
