# Generated by Django 2.0.4 on 2018-06-20 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0022_competitionstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionstat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
