# Generated by Django 2.0.4 on 2018-06-20 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prode', '0023_auto_20180620_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionstat',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prode.Competition'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionstat',
            unique_together={('user', 'comp')},
        ),
    ]
