# Generated by Django 2.0.4 on 2018-06-20 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0024_auto_20180620_1954'),
        ('prode', '0020_competition_available'),
    ]

    operations = [
    ]
