# Generated by Django 2.0.4 on 2018-06-21 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0025_merge_20180620_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionstat',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comps', to='prode.Competition'),
        ),
        migrations.AlterField(
            model_name='competitionstat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comps', to=settings.AUTH_USER_MODEL),
        ),
    ]
