# Generated by Django 2.0.4 on 2018-06-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0026_auto_20180621_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='calculated',
            field=models.BooleanField(default=False),
        ),
    ]
