# Generated by Django 2.0.4 on 2018-07-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prode', '0027_bet_calculated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together=set(),
        ),
    ]
