# Generated by Django 2.0.7 on 2018-07-04 02:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prode', '0028_auto_20180703_1638'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together={('user', 'match')},
        ),
    ]
